//app
export const APP_SET_DARK_MODE = 'APP_SET_DARK_MODE';

//net info
export const NET_INFO_REQUEST = 'NET_INFO_REQUEST';
export const NET_INFO_SUCCESS = 'NET_INFO_SUCCESS';
export const NET_INFO_FAILED = 'NET_INFO_FAILED';

//characters
export const CHARACTERS_REQUEST = 'CHARACTERS_REQUEST';
export const CHARACTERS_SUCCESS = 'CHARACTERS_SUCCESS';
export const CHARACTERS_FAILED = 'CHARACTERS_FAILED';

//episodes
export const EPISODE_REQUEST = 'EPISODE_REQUEST';
export const EPISODE_SUCCESS = 'EPISODE_SUCCESS';
export const EPISODE_FAILED = 'EPISODE_FAILED';